log:
  log_dir: "./logs"
  log_filename: "app.log"
  log_level: "INFO"
  use_debug_mode: true
openai:
  email: "user1"
  password: "123456"
  session_token: ""
  proxy: ""
app:
  host: "0.0.0.0"
  port: 7777